sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - PIP_DJANGO='Django>=1.11,<2.0'
  - PIP_DJANGO='Django>=2.0,<2.1'
  - PIP_DJANGO='Django>=2.1,<2.2'
  - PIP_DJANGO='Django>=2.2,<3.0'
  - PIP_DJANGO='Django>=3.0,<3.1'
matrix:
  exclude:
    - env: PIP_DJANGO='Django>=2.0,<2.1'
      python: "2.7"
    - env: PIP_DJANGO='Django>=2.1,<2.2'
      python: "2.7"
install:
  - "pip install $PIP_DJANGO pyyaml coveralls pytest-django"
  - "pip install -e ."
script:
  coverage run $VIRTUAL_ENV/bin/py.test --ds=test_settings typedmodels/tests.py
after_success:
  coveralls
